### ISSUE TITLE
missing require rack/version causing issues with sidekiq

### ISSUE THREAD

**Issue by neontuna** [rails/propshaft#184]
This has actually already been fixed with this commit

https://github.com/rails/propshaft/commit/2d884c2af4e7ce3893e94707fe8f7d50d5970f44

But unfortunately the commit landed after the latest release (0.8.0).  

In the process of upgrading an older Rails code base to 7 and so maybe this error is due to something else.  Everything else is working well but trying to boot sidekiq runs into this error

```
[swarm] Preloading Bundler groups ["default"]
bundler: failed to load command: sidekiqswarm (/Users/j/.rbenv/versions/3.3.0/bin/sidekiqswarm)
/Users/j/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/propshaft-0.8.0/lib/propshaft/server.rb:43:in `<class:Server>': uninitialized constant Rack::RELEASE (NameError)

    if Gem::Version.new(Rack::RELEASE) < Gem::Version.new("3")
                            ^^^^^^^^^
	from /Users/j/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/propshaft-0.8.0/lib/propshaft/server.rb:3:in `<top (required)>'
	from /Users/j/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /Users/j/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/j/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/propshaft-0.8.0/lib/propshaft/assembly.rb:4:in `<top (required)>'
```

**Comment by theodorton** [comment]
Can you try setting `gem "propshaft", require: false` and in `config/application.rb`:

```rb
# ...
Bundler.require(*Rails.groups)
require 'rack/version'
require 'propshaft'
# ...
```

**Comment by theodorton** [comment]
Closing as this should be resolved in main
