### ISSUE TITLE
v0.4.2 appears to be broken

### ISSUE THREAD

**Issue by rmacklin** [rails/propshaft#41]
Upgrading from propshaft v0.4.1 to v0.4.2 introduced this error on application initialization:
```
undefined local variable or method `paths' for #<Propshaft::Railtie:0x00005cd9e1dc97c8> (NameError)
```
from this line:
https://github.com/rails/propshaft/blob/b47f43b713c65399a7243e6c382fb9c454ad2c45/lib/propshaft/railtie.rb#L39

<details>

<summary>Full stack trace from trying to load a rails console</summary>

```
$ bundle exec rails c
Traceback (most recent call last):
        37: from bin/rails:4:in `<main>'
        36: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        35: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        34: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
        33: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        32: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        31: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/rails-14f190f33710/railties/lib/rails/commands.rb:18:in `<main>'
        30: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/rails-14f190f33710/railties/lib/rails/command.rb:48:in `invoke'
        29: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/rails-14f190f33710/railties/lib/rails/command/base.rb:87:in `perform'
        28: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        27: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        26: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        25: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/rails-14f190f33710/railties/lib/rails/commands/console/console_command.rb:101:in `perform'
        24: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/rails-14f190f33710/railties/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
        23: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/rails-14f190f33710/railties/lib/rails/command/actions.rb:28:in `require_environment!'
        22: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/rails-14f190f33710/railties/lib/rails/application.rb:345:in `require_environment!'
        21: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
        20: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        19: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        18: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
        17: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        16: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        15: from /home/richard/playground/rails-propshaft-example/config/environment.rb:5:in `<main>'
        14: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/rails-14f190f33710/railties/lib/rails/application.rb:369:in `initialize!'
        13: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/rails-14f190f33710/railties/lib/rails/initializable.rb:60:in `run_initializers'
        12: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
        11: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
        10: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
         9: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `call'
         8: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each'
         7: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
         6: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
         5: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
         4: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
         3: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/rails-14f190f33710/railties/lib/rails/initializable.rb:61:in `block in run_initializers'
         2: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/rails-14f190f33710/railties/lib/rails/initializable.rb:32:in `run'
         1: from /home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/rails-14f190f33710/railties/lib/rails/initializable.rb:32:in `instance_exec'
/home/richard/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/propshaft-0.4.2/lib/propshaft/railtie.rb:39:in `block in <class:Railtie>': undefined local variable or method `paths' for #<Propshaft::Railtie:0x00005cd9e1dc97c8> (NameError)
Did you mean?  Pathname
```

</details>

I added a test app for integration testing in #20, and it's producing the same error after rebasing:
https://github.com/rails/propshaft/runs/4414708235?check_suite_focus=true#step:4:4

66ce0f889377b81a28b1dd1fbe245868a047d46f seems to be the commit that broke this. If I revert that commit, the integration test passes:
https://github.com/rmacklin/propshaft/runs/4414863639?check_suite_focus=true#step:4:10

**Comment by rmacklin** [comment]
I've opened https://github.com/rails/propshaft/pull/42 to revert that commit

**Comment by rmacklin** [comment]
cc @rafaelfranca
